stages:
 - compile
 - test
 
language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

jobs:
   include:
      - stage: compile
        script: make
      - stage: test
        script: make test
